name: card_settings
description: A flutter package for building card based settings forms. This includes a library of pre-built form field widgets.
version: 3.5.1
homepage: https://github.com/codegrue/card_settings
issue_tracker: https://github.com/codegrue/card_settings/issues

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  intl: 
  meta: 
  extended_masked_text: 
  flutter_cupertino_settings: 
  flutter_material_pickers: 
  pattern_formatter: 
  flutter_multi_formatter: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  test:
  mockito: ^5.3.2

environment:
  sdk: ">=2.12.0 <4.0.0"

flutter:
  uses-material-design: true
